/*
 * Generated by dtrace(1M).
 */

#ifndef	_PROBES_DNSCRYPT_PROXY_H
#define	_PROBES_DNSCRYPT_PROXY_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define DNSCRYPT_PROXY_STABILITY "___dtrace_stability$dnscrypt_proxy$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define DNSCRYPT_PROXY_TYPEDEFS "___dtrace_typedefs$dnscrypt_proxy$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	DNSCRYPT_PROXY_CERTS_UPDATE_DONE(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$certs__update__done$v1$756e7369676e65642063686172205b33325d(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$certs__update__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_COMMUNICATION() \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$certs__update__error__communication$v1(); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_COMMUNICATION_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$certs__update__error__communication$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_NOCERTS() \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$certs__update__error__nocerts$v1(); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_NOCERTS_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$certs__update__error__nocerts$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_SECURITY() \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$certs__update__error__security$v1(); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_SECURITY_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$certs__update__error__security$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_CERTS_UPDATE_RECEIVED() \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$certs__update__received$v1(); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_RECEIVED_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$certs__update__received$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_CERTS_UPDATE_RETRY() \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$certs__update__retry$v1(); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_RETRY_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$certs__update__retry$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_CERTS_UPDATE_START() \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$certs__update__start$v1(); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$certs__update__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_CURVE_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__curve_done$v1$766f6964202a$73697a655f74(arg0, arg1); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__curve_done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_CURVE_ERROR(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__curve_error$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_ERROR_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__curve_error$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_CURVE_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__curve_start$v1$766f6964202a$73697a655f74(arg0, arg1); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__curve_start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_DONE(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__plugins__post__done$v1$766f6964202a$73697a655f74$73697a655f74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__plugins__post__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_ERROR(arg0, arg1) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__plugins__post__error$v1$766f6964202a$696e74(arg0, arg1); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_ERROR_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__plugins__post__error$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_START(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__plugins__post__start$v1$766f6964202a$73697a655f74$73697a655f74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_START_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__plugins__post__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_DONE(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__plugins__pre__done$v1$766f6964202a$73697a655f74$73697a655f74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__plugins__pre__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_ERROR(arg0, arg1) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__plugins__pre__error$v1$766f6964202a$696e74(arg0, arg1); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_ERROR_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__plugins__pre__error$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_START(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__plugins__pre__start$v1$766f6964202a$73697a655f74$73697a655f74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__plugins__pre__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_TCP_DONE(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__tcp__done$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__tcp__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_TCP_NETWORK_ERROR(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__tcp__network_error$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_NETWORK_ERROR_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__tcp__network_error$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_TCP_OVERLOADED() \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__tcp__overloaded$v1(); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_OVERLOADED_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__tcp__overloaded$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_CONNECTED(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__tcp__proxy_resolver__connected$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_CONNECTED_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__tcp__proxy_resolver__connected$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_DONE(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__tcp__proxy_resolver__done$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__tcp__proxy_resolver__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_GOT_INVALID_REPLY(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__tcp__proxy_resolver__got_invalid_reply$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_GOT_INVALID_REPLY_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__tcp__proxy_resolver__got_invalid_reply$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_NETWORK_ERROR(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__tcp__proxy_resolver__network_error$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_NETWORK_ERROR_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__tcp__proxy_resolver__network_error$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_REPLIED(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__tcp__proxy_resolver__replied$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_REPLIED_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__tcp__proxy_resolver__replied$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_START(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__tcp__proxy_resolver__start$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_START_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__tcp__proxy_resolver__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_TCP_REPLIED(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__tcp__replied$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_REPLIED_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__tcp__replied$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_TCP_START(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__tcp__start$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_START_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__tcp__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_TCP_TIMEOUT(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__tcp__timeout$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_TIMEOUT_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__tcp__timeout$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UDP_DONE(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__udp__done$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__udp__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UDP_NETWORK_ERROR(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__udp__network_error$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_NETWORK_ERROR_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__udp__network_error$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UDP_OVERLOADED() \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__udp__overloaded$v1(); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_OVERLOADED_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__udp__overloaded$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_DONE(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__udp__proxy_resolver__done$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__udp__proxy_resolver__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_GOT_INVALID_REPLY(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__udp__proxy_resolver__got_invalid_reply$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_GOT_INVALID_REPLY_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__udp__proxy_resolver__got_invalid_reply$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_REPLIED(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__udp__proxy_resolver__replied$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_REPLIED_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__udp__proxy_resolver__replied$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_START(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__udp__proxy_resolver__start$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_START_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__udp__proxy_resolver__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UDP_REPLIED(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__udp__replied$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_REPLIED_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__udp__replied$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UDP_RETRY(arg0, arg1) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__udp__retry$v1$766f6964202a$756e7369676e65642063686172(arg0, arg1); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_RETRY_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__udp__retry$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UDP_RETRY_SCHEDULED(arg0, arg1) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__udp__retry_scheduled$v1$766f6964202a$756e7369676e65642063686172(arg0, arg1); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_RETRY_SCHEDULED_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__udp__retry_scheduled$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UDP_START(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__udp__start$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_START_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__udp__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UDP_TIMEOUT(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__udp__timeout$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_TIMEOUT_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__udp__timeout$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UDP_TRUNCATED(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__udp__truncated$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_TRUNCATED_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__udp__truncated$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__uncurve_done$v1$766f6964202a$73697a655f74(arg0, arg1); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__uncurve_done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_ERROR(arg0) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__uncurve_error$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_ERROR_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__uncurve_error$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$request__uncurve_start$v1$766f6964202a$73697a655f74(arg0, arg1); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$request__uncurve_start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	DNSCRYPT_PROXY_STATUS_REQUESTS_ACTIVE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_TYPEDEFS); \
	__dtrace_probe$dnscrypt_proxy$status__requests__active$v1$756e7369676e656420696e74$756e7369676e656420696e74(arg0, arg1); \
	__asm__ volatile(".reference " DNSCRYPT_PROXY_STABILITY); \
} while (0)
#define	DNSCRYPT_PROXY_STATUS_REQUESTS_ACTIVE_ENABLED() \
	({ int _r = __dtrace_isenabled$dnscrypt_proxy$status__requests__active$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$dnscrypt_proxy$certs__update__done$v1$756e7369676e65642063686172205b33325d(unsigned char [32]);
extern int __dtrace_isenabled$dnscrypt_proxy$certs__update__done$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$certs__update__error__communication$v1(void);
extern int __dtrace_isenabled$dnscrypt_proxy$certs__update__error__communication$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$certs__update__error__nocerts$v1(void);
extern int __dtrace_isenabled$dnscrypt_proxy$certs__update__error__nocerts$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$certs__update__error__security$v1(void);
extern int __dtrace_isenabled$dnscrypt_proxy$certs__update__error__security$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$certs__update__received$v1(void);
extern int __dtrace_isenabled$dnscrypt_proxy$certs__update__received$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$certs__update__retry$v1(void);
extern int __dtrace_isenabled$dnscrypt_proxy$certs__update__retry$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$certs__update__start$v1(void);
extern int __dtrace_isenabled$dnscrypt_proxy$certs__update__start$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__curve_done$v1$766f6964202a$73697a655f74(const void *, size_t);
extern int __dtrace_isenabled$dnscrypt_proxy$request__curve_done$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__curve_error$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__curve_error$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__curve_start$v1$766f6964202a$73697a655f74(const void *, size_t);
extern int __dtrace_isenabled$dnscrypt_proxy$request__curve_start$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__plugins__post__done$v1$766f6964202a$73697a655f74$73697a655f74(const void *, size_t, size_t);
extern int __dtrace_isenabled$dnscrypt_proxy$request__plugins__post__done$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__plugins__post__error$v1$766f6964202a$696e74(const void *, int);
extern int __dtrace_isenabled$dnscrypt_proxy$request__plugins__post__error$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__plugins__post__start$v1$766f6964202a$73697a655f74$73697a655f74(const void *, size_t, size_t);
extern int __dtrace_isenabled$dnscrypt_proxy$request__plugins__post__start$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__plugins__pre__done$v1$766f6964202a$73697a655f74$73697a655f74(const void *, size_t, size_t);
extern int __dtrace_isenabled$dnscrypt_proxy$request__plugins__pre__done$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__plugins__pre__error$v1$766f6964202a$696e74(const void *, int);
extern int __dtrace_isenabled$dnscrypt_proxy$request__plugins__pre__error$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__plugins__pre__start$v1$766f6964202a$73697a655f74$73697a655f74(const void *, size_t, size_t);
extern int __dtrace_isenabled$dnscrypt_proxy$request__plugins__pre__start$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__tcp__done$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__tcp__done$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__tcp__network_error$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__tcp__network_error$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__tcp__overloaded$v1(void);
extern int __dtrace_isenabled$dnscrypt_proxy$request__tcp__overloaded$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__tcp__proxy_resolver__connected$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__tcp__proxy_resolver__connected$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__tcp__proxy_resolver__done$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__tcp__proxy_resolver__done$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__tcp__proxy_resolver__got_invalid_reply$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__tcp__proxy_resolver__got_invalid_reply$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__tcp__proxy_resolver__network_error$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__tcp__proxy_resolver__network_error$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__tcp__proxy_resolver__replied$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__tcp__proxy_resolver__replied$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__tcp__proxy_resolver__start$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__tcp__proxy_resolver__start$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__tcp__replied$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__tcp__replied$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__tcp__start$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__tcp__start$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__tcp__timeout$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__tcp__timeout$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__udp__done$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__udp__done$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__udp__network_error$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__udp__network_error$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__udp__overloaded$v1(void);
extern int __dtrace_isenabled$dnscrypt_proxy$request__udp__overloaded$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__udp__proxy_resolver__done$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__udp__proxy_resolver__done$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__udp__proxy_resolver__got_invalid_reply$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__udp__proxy_resolver__got_invalid_reply$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__udp__proxy_resolver__replied$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__udp__proxy_resolver__replied$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__udp__proxy_resolver__start$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__udp__proxy_resolver__start$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__udp__replied$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__udp__replied$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__udp__retry$v1$766f6964202a$756e7369676e65642063686172(const void *, unsigned char);
extern int __dtrace_isenabled$dnscrypt_proxy$request__udp__retry$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__udp__retry_scheduled$v1$766f6964202a$756e7369676e65642063686172(const void *, unsigned char);
extern int __dtrace_isenabled$dnscrypt_proxy$request__udp__retry_scheduled$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__udp__start$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__udp__start$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__udp__timeout$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__udp__timeout$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__udp__truncated$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__udp__truncated$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__uncurve_done$v1$766f6964202a$73697a655f74(const void *, size_t);
extern int __dtrace_isenabled$dnscrypt_proxy$request__uncurve_done$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__uncurve_error$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$dnscrypt_proxy$request__uncurve_error$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$request__uncurve_start$v1$766f6964202a$73697a655f74(const void *, size_t);
extern int __dtrace_isenabled$dnscrypt_proxy$request__uncurve_start$v1(void);
extern void __dtrace_probe$dnscrypt_proxy$status__requests__active$v1$756e7369676e656420696e74$756e7369676e656420696e74(unsigned int, unsigned int);
extern int __dtrace_isenabled$dnscrypt_proxy$status__requests__active$v1(void);

#else

#define	DNSCRYPT_PROXY_CERTS_UPDATE_DONE(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_COMMUNICATION() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_COMMUNICATION_ENABLED() (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_NOCERTS() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_NOCERTS_ENABLED() (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_SECURITY() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_SECURITY_ENABLED() (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_RECEIVED() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_RECEIVED_ENABLED() (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_RETRY() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_RETRY_ENABLED() (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_START() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_DONE(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_ERROR(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_START(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_DONE(arg0, arg1, arg2) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_ERROR(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_START(arg0, arg1, arg2) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_DONE(arg0, arg1, arg2) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_ERROR(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_START(arg0, arg1, arg2) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_DONE(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_NETWORK_ERROR(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_NETWORK_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_OVERLOADED() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_OVERLOADED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_CONNECTED(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_CONNECTED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_DONE(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_GOT_INVALID_REPLY(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_GOT_INVALID_REPLY_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_NETWORK_ERROR(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_NETWORK_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_REPLIED(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_REPLIED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_START(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_REPLIED(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_REPLIED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_START(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_TIMEOUT(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_TIMEOUT_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_DONE(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_NETWORK_ERROR(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_NETWORK_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_OVERLOADED() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_OVERLOADED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_DONE(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_GOT_INVALID_REPLY(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_GOT_INVALID_REPLY_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_REPLIED(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_REPLIED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_START(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_REPLIED(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_REPLIED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_RETRY(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_RETRY_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_RETRY_SCHEDULED(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_RETRY_SCHEDULED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_START(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_TIMEOUT(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_TIMEOUT_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_TRUNCATED(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_TRUNCATED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_DONE(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_ERROR(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_START(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_STATUS_REQUESTS_ACTIVE(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_STATUS_REQUESTS_ACTIVE_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _PROBES_DNSCRYPT_PROXY_H */
