
#ifndef __PROBES_NO_DTRACE_H__
# define __PROBES_NO_DTRACE_H__ 1

#define	DNSCRYPT_PROXY_CERTS_UPDATE_DONE(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_COMMUNICATION() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_COMMUNICATION_ENABLED() (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_NOCERTS() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_NOCERTS_ENABLED() (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_SECURITY() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_ERROR_SECURITY_ENABLED() (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_RECEIVED() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_RECEIVED_ENABLED() (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_RETRY() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_RETRY_ENABLED() (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_START() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_CERTS_UPDATE_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_DONE(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_ERROR(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_START(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_CURVE_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_DONE(arg0, arg1, arg2) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_ERROR(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_START(arg0, arg1, arg2) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_POST_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_DONE(arg0, arg1, arg2) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_ERROR(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_START(arg0, arg1, arg2) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_PLUGINS_PRE_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_DONE(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_NETWORK_ERROR(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_NETWORK_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_OVERLOADED() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_OVERLOADED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_CONNECTED(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_CONNECTED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_DONE(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_GOT_INVALID_REPLY(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_GOT_INVALID_REPLY_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_NETWORK_ERROR(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_NETWORK_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_REPLIED(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_REPLIED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_START(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_PROXY_RESOLVER_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_REPLIED(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_REPLIED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_START(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_TIMEOUT(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_TCP_TIMEOUT_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_DONE(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_NETWORK_ERROR(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_NETWORK_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_OVERLOADED() \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_OVERLOADED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_DONE(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_GOT_INVALID_REPLY(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_GOT_INVALID_REPLY_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_REPLIED(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_REPLIED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_START(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_PROXY_RESOLVER_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_REPLIED(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_REPLIED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_RETRY(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_RETRY_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_RETRY_SCHEDULED(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_RETRY_SCHEDULED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_START(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_TIMEOUT(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_TIMEOUT_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_TRUNCATED(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UDP_TRUNCATED_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_DONE(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_DONE_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_ERROR(arg0) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_ERROR_ENABLED() (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_START(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_REQUEST_UNCURVE_START_ENABLED() (0)
#define	DNSCRYPT_PROXY_STATUS_REQUESTS_ACTIVE(arg0, arg1) \
do { \
	} while (0)
#define	DNSCRYPT_PROXY_STATUS_REQUESTS_ACTIVE_ENABLED() (0)

#endif
