name: 🌱 Feature request
description: If you know how AdGuard for iOS can be improved
labels: ["Feature request"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Details
      description: What happened?
      placeholder: Is your feature request related to a problem? Please add a clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: how_it_should_be
    attributes:
      label: Proposed solution
      description:
      placeholder: Describe the solution you'd like in a clear and concise manner.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Alternative solution
      description:
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        Upvote [important issues](https://github.com/AdguardTeam/AdguardForiOS/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+) with a :+1: