# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

# Configuration
COMMIT_MESSAGE = "skipci: Automatic version increment"

def commit_ag_build_bump()
  FastlaneCore::CommandExecutor.execute(command: "git add ..",
                                        print_all: true,
                                        error: proc do |error_output|
                                          UI.error("Failed to run git add: #{error_output}")
                                        end)
  FastlaneCore::CommandExecutor.execute(command: "git commit -m '#{COMMIT_MESSAGE}'",
                                        print_all: true,
                                        error: proc do |error_output|
                                          UI.error("Failed to run git commit: #{error_output}")
                                        end)
end

def zip_archive()
  archive_path = "../#{ENV['OUTPUT_DIRECTORY']}/#{ENV['ARCHIVE_NAME']}"
  command = "/usr/bin/ditto -c -k --keepParent \"#{archive_path}\" \"#{archive_path}.zip\""

  FastlaneCore::CommandExecutor.execute(command: command,
                                        print_all: true,
                                        error: proc do |error_output|
                                          UI.error("Failed to run zip_archive: #{error_output}")
                                        end)
end

def clean()
  FastlaneCore::CommandExecutor.execute(command: "rm -rf ../#{ENV['OUTPUT_DIRECTORY']}",
                                        print_all: true,
                                        error: proc do |error_output|
                                          UI.error("Failed to run clean: #{error_output}")
                                        end)
end

platform :ios do
  desc "Runs unit tests"
  lane :tests do
    run_tests(
      scheme: ENV['BUILD_SCHEME'],
      output_types: "junit",
      clean: true,
      code_coverage: true,
    )
  end

  desc "Builds app for appstore"
  lane :build do
    clean()

    match(type: "appstore", readonly: true)
    build_app(
      scheme: ENV['BUILD_SCHEME'],
      output_directory: ENV['OUTPUT_DIRECTORY'],
      include_bitcode: false,
      include_symbols: true,
      archive_path: "#{ENV['OUTPUT_DIRECTORY']}/#{ENV['ARCHIVE_NAME']}",
    )
    write_build_info(
      xcconfig: ENV['BUILD_NUMBER_XCCONFIG_PATH'],
      build_info_output: "#{ENV['OUTPUT_DIRECTORY']}/build.txt",
    )
    zip_archive()
  end

  desc "Builds adhoc build for inner testing"
  lane :adhoc do
    clean()

    match(type: "adhoc", force_for_new_devices: true)
    build_app(
      scheme: ENV['BUILD_SCHEME'],
      output_directory: ENV['OUTPUT_DIRECTORY'],
      include_bitcode: false,
      include_symbols: true,
      archive_path: "#{ENV['OUTPUT_DIRECTORY']}/#{ENV['ARCHIVE_NAME']}",
    )
    write_build_info(
      xcconfig: ENV['XCCONFIG_PATH'],
      build_info_output: "#{ENV['OUTPUT_DIRECTORY']}/build.txt",
    )
    zip_archive()
  end

  desc "Increments the build number and commits to the repo"
  lane :increment do
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    # Increment the build number (not the version number)
    increment_ag_build(xcconfig: ENV['BUILD_NUMBER_XCCONFIG_PATH'])

    # Commit
    commit_ag_build_bump()

    # Push the new commit and tag back to your git remote
    push_to_git_remote
  end

  desc "Uploads the build to testflight"
  lane :testflight_beta do
    # Uploads the build without actually submitting it
    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      ipa: "#{ENV['OUTPUT_DIRECTORY']}/#{ENV['IPA_NAME']}"
    )
  end
end

lane :prepare do
  get_certificates(
    development: true,
    platform: "macos",
    username: "apple-dev@adguard.com",
    team_id: "N33TQXN8C7",
    output_path: "./build",
  )
  get_certificates(
    development: false,
    platform: "macos",
    username: "apple-dev@adguard.com",
    team_id: "N33TQXN8C7",
    output_path: "./build",
  )

  # get_certificates creates .p12 and .cer files in the build directory

  match(type: "development", readonly: true, platform: "ios", team_id: "N33TQXN8C7")
  match(type: "appstore", readonly: true, platform: "ios", team_id: "N33TQXN8C7")
  match(type: "adhoc", readonly: true, platform: "ios", team_id: "N33TQXN8C7")
end
