
// Objective-C API for talking to the following Go packages
//
// github.com/AdguardTeam/dnsproxy/mobile
//
// Current version of dnsproxy: v0.18.2
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mobile_FRAMEWORK_H__
#define __Mobile_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Universe.objc.h"

#endif
